### ISSUE TITLE
Publish on JetBrains Plugin Collection

### ISSUE THREAD

**Issue by jcope2013** [kristianmandrup/emberjs-plugin#1]
the instructions seem to suggest you can download it directly through the JetBrains plugin collection but when I go there, I can't seem to find it? EmberJS yields no results

**Comment by QuantumInformation** [comment]
Any ideas when we will see this on the plugin repo?

**Comment by kristianmandrup** [comment]
I'm not working on this project anymore since I've stopped using Ember for the time being.
You are most welcome to fork it and continue development...

**Comment by QuantumInformation** [comment]
I've never developed a plugin for IDEA, maybe we should ping jetbrains to see if they can help?

**Comment by kristianmandrup** [comment]
I already had contact and some assistance from them.

dennis.ushakov@jetbrains.com
