### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by Turbo87** [kristianmandrup/emberjs-plugin#4]
I was thinking about forking the project and continuing your work, but I can't legally do that without some kind of license attached to the project. Please choose one and add it to the README file (or a separate LICENSE file), otherwise others are not allowed to reuse your code!

**Comment by kristianmandrup** [comment]
Done. Please go ahead! Make my day ;)

**Comment by Turbo87** [comment]
FYI I couldn't really figure out what parts were still from the Angular plugin and what parts still work with Ember and decided to start from scratch: https://github.com/Turbo87/intellij-emberjs

Feedback would be very welcome!
